import { Scholarship } from './types'

export const demoScholarships: (Scholarship & {
  winProbability: number
  tags: string[]
  matchReasons: string[]
})[] = [
  {
    id: "demo-1",
    title: "STEM Excellence Scholarship",
    source_url: "https://example.com/stem-scholarship",
    grade_level_summary: "College",
    amount: "$10,000",
    citizenship_status: "U.S. Citizens",
    academic_interest: "STEM",
    other_background_interest: undefined,
    state_residency: undefined,
    minimum_gpa: 3.5,
    winProbability: 0.87,
    tags: ["STEM", "College", "High Value"],
    matchReasons: [
      "3.8 GPA exceeds 3.5 requirement",
      "Computer Science major matches STEM focus",
      "Research experience aligns with criteria",
    ],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-2",
    title: "Future Leaders Award",
    source_url: "https://example.com/future-leaders",
    grade_level_summary: "College",
    amount: "$5,000",
    citizenship_status: "U.S. Citizens",
    academic_interest: "All Majors",
    other_background_interest: "Leadership",
    state_residency: undefined,
    minimum_gpa: 3.0,
    winProbability: 0.92,
    tags: ["Leadership", "Community Service", "All Majors"],
    matchReasons: [
      "100+ volunteer hours exceed requirement",
      "President of 2 student organizations",
      "Strong leadership essay portfolio",
    ],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-3",
    title: "Women in Technology Grant",
    source_url: "https://example.com/women-in-tech",
    grade_level_summary: "Graduate",
    amount: "$7,500",
    citizenship_status: "U.S. Citizens",
    academic_interest: "Technology",
    other_background_interest: "Women",
    state_residency: undefined,
    minimum_gpa: 3.2,
    winProbability: 0.78,
    tags: ["Women", "Technology", "Graduate"],
    matchReasons: [
      "Computer Science graduate student",
      "Tech internship experience",
      "Strong academic performance",
    ],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-4",
    title: "Community Impact Scholarship",
    source_url: "https://example.com/community-impact",
    grade_level_summary: "College",
    amount: "$3,000",
    citizenship_status: "U.S. Citizens",
    academic_interest: "All Majors",
    other_background_interest: "Community Service",
    state_residency: "PA",
    minimum_gpa: 2.5,
    winProbability: 0.85,
    tags: ["Community Service", "Local", "College"],
    matchReasons: [
      "Extensive local volunteer work",
      "Community organizing experience",
      "Strong recommendation letters",
    ],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-5",
    title: "Academic Excellence Award",
    source_url: "https://example.com/academic-excellence",
    grade_level_summary: "College",
    amount: "$8,000",
    citizenship_status: "U.S. Citizens",
    academic_interest: "All Majors",
    other_background_interest: undefined,
    state_residency: undefined,
    minimum_gpa: 3.5,
    winProbability: 0.89,
    tags: ["Academic", "High GPA", "All Majors"],
    matchReasons: [
      "3.8 GPA exceeds 3.5 requirement",
      "Dean's List multiple semesters",
      "Strong academic references",
    ],
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
]
